### ISSUE TITLE
"open external site" icon

### ISSUE THREAD

**Issue by placoderm** [planetabhi/sargam-icons#17]
I don't think you have the standard "open on external site" icon. For example we see it commonly on wikipedia:

![image](https://github.com/user-attachments/assets/f46f3564-c436-4eea-beb8-b8f1360aa460)

Personally I'm not keen on the filled in triangle bit. Feels inconsistent. But you have such great design skill I'm sure you can make something good if you like to add this.

Thanks!

**Comment by planetabhi** [comment]
Thanks, I'll add variants for this over this weekend.

**Comment by placoderm** [comment]
Thanks!

**Comment by planetabhi** [comment]
<img width="444" alt="external-link" src="https://github.com/user-attachments/assets/1c0e8ded-ff9b-420f-a279-1b152bba5142">

Added some options. 🙌

**Comment by placoderm** [comment]
Nice!! The second one is exactly what I'm after. Thanks!
