### ISSUE TITLE
Copyright icon

### ISSUE THREAD

**Issue by huntercox** [planetabhi/sargam-icons#6]
I'd like to request a copyright icon in this style.

I love the look and feel of the 3 styles and the 24x24 grid. I'm using the icons for more of decorations on a web design, rather than action-orientated UI buttons, but still finding ways to use them.

**Comment by planetabhi** [comment]
![copyright_preview](https://user-images.githubusercontent.com/1704622/232232186-501f9f0b-4ab6-4ef3-b778-bc0917f91095.png)

Added to the set. 🙌

**Comment by huntercox** [comment]
Thank you so much! It looks fantastic!
