### ISSUE TITLE
icon for build and json

### ISSUE THREAD

**Issue by placoderm** [planetabhi/sargam-icons#9]
I was using your wonderful icons in a project recently and needed a button to represent a build function. I ended up using the play triangle in a circle. Maybe an icon with a hammer might also work. I'm not sure.

I also needed a button to download a json version of some data. I ended up getting a double curly bracket icon `{ }` from another set. 

Perhaps these are too obscure, but I thought I would mention. Thanks!

**Comment by planetabhi** [comment]
<img width="646" alt="preview" src="https://github.com/planetabhi/sargam-icons/assets/1704622/fe00f5a9-b688-4b27-bd06-f641458341d8">
There you go!

**Comment by placoderm** [comment]
Great! Thanks!
